/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/robots.txt' | '/site.webmanifest' | '/sitemap.xml' | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/robots.txt'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
